[project]
name = "syssim"
description = "General purpose multi-system simulation utilizing graph structure."
version = "1.0.0"
authors = [
    { name = "Josef Biberstein", email = "josef.business@protonmail.com" }
]
dependencies = [
    "matplotlib",
    "rustworkx",
    "toml",
    "tqdm",
    "numpy"
]

[project.optional-dependencies]
test = [
    "pytest>=7.0",
    "scipy"
]