[NodeSCRigidBodyRotationDynamics-1]
[estimator]
inertia = [[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]]
[encoder_1]
w_noise = 0.001
w_bias = 0.0
[encoder_2]
w_noise = 0.001
w_bias = 0.0
[encoder_3]
w_noise = 0.001
w_bias = 0.0
[encoder_4]
w_noise = 0.001
w_bias = 0.0
[node_imu1]
w_noise = 0.001
a_noise = 0.001
w_bias = 0.0
a_bias = 0.0
[node_sru1]
sru_cross_noise = 0.01
sru_roll_noise = 0.01
[node_imu2]
w_noise = 0.001
a_noise = 0.001
w_bias = 0.0
a_bias = 0.0
[node_sru2]
sru_cross_noise = 0.01
sru_roll_noise = 0.01
[rwa_1]
rwa_inertia = 0.25e-1
[rwa_2]
rwa_inertia = 0.25e-1
[rwa_3]
rwa_inertia = 0.25e-1
[rwa_4]
rwa_inertia = 0.25e-1
[NodePointingControlSimple-1]
pointing_kp = 3.0
pointing_kd = 2.0
pointing_ki = 0.0 #1e-2
i_mag_limit = 0.1
i_enable_limit = 0.2
[viz_true_rate]
title = "True Rate"
xlabel = "Time (s)"
ylabel = "Rate (rad/s)"
[viz_imu_rate]
title = "IMU Rate"
xlabel = "Time (s)"
ylabel = "Rate (rad/s)"
[viz_torque]
title = "Torque"
xlabel = "Time (s)"
ylabel = "Torque (Nm)"
[viz_pointing]
title = "Pointing"
xlabel = "Time (s)"
ylabel = "quaternion"
[viz_est_rate]
title = "Estimated Rate"
xlabel = "Time (s)"
ylabel = "Rate (rad/s)"
[viz_est_pointing]
title = "Estimated Pointing"
xlabel = "Time (s)"
ylabel = "quaternion"